new/urls.py
from django.conf.urls import url
from django.contrib import admin

from simuli import views

from .views import (
    IntroView,

    TeamView,
    ProductView,
    ProductionView,
    SupplyView,
    BoardView,
    ResultView,
    ProductUpdateView,
    ForcastCreateView,
    SupplyCreateView,
    VendorCreateView,
    UserProfileUpdateView,
    SupplyUpdateView,
    SupplyUpdateView2,
    SupplyUpdateView3,
    SupplyUpdateView4,
    SendInvite,
    TestView,
    ReportView,

    )

urlpatterns = [
    url(r'^$', IntroView, name='intro'),
    url(r'^design$', ProductView, name='design'),
    url(r'^team', TeamView, name='team'),
    url(r'^production', ProductionView, name='production'),
    url(r'^supply$', SupplyView, name='supply'),
    url(r'^board', BoardView, name='board'),
    url(r'^result', ResultView, name='results'),
    url(r'^test', TestView, name='test'),
    url(r'^report', ReportView, name='report'),
    url(r'^invite', SendInvite.as_view(), name='invite'),

    # url(r'^videos/(?P<pk>\d+)/$', VideoDetailView.as_view(), name='video-detail'),
    #url(r'^(?P<slug>[\w-]+)/$', VideoDetailView.as_view(), name='detail'),
    url(r'^forcast/(?P<pk>[0-9]+)/', ForcastCreateView.as_view(), name='forcastupdate'),
    url(r'^createsupply$', SupplyCreateView, name='supplycreate'),
    url(r'^design/(?P<pk>[0-9]+)/', ProductUpdateView.as_view(), name='designupdate'),
    url(r'^createvendor$', VendorCreateView, name='createvendor'),
    url(r'^profile/(?P<pk>[0-9]+)/', UserProfileUpdateView.as_view(), name='profileupdate'),
    url(r'^supply/(?P<pk>[0-9]+)/', SupplyUpdateView.as_view(), name='supplyupdate'),
    url(r'^2supply/(?P<pk>[0-9]+)/', SupplyUpdateView2.as_view(), name='supplyupdate2'),
    url(r'^3supply/(?P<pk>[0-9]+)/', SupplyUpdateView3.as_view(), name='supplyupdate3'),
    url(r'^4supply/(?P<pk>[0-9]+)/', SupplyUpdateView4.as_view(), name='supplyupdate4'),
     
    #url(r'^(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),  



]

simuli/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from .views import HomeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^new/', include('new.urls', namespace='vendor')),
    url(r'^accounts/', include('allauth.urls')),
    #url(r'^invitations/accept-invite/(?P<key>\w+)/?$', AcceptInviteView.as_view(), name='accept-invite'),
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),





    
    url(r'^new/', include('new.urls', namespace='vendor')),
    url(r'^accounts/', include('allauth.urls')), 
    	


]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/case/budget.html
{% extends 'base.html' %}

{% block content %}
    {% if user.is_authenticated %}
    <h3>Hello, {{ user.username }} </h3>
    {{ user.email }}
    {% endif %}

{% endblock content %}

templates/case/case.html
{% load staticfiles %}

{% block content %}
<link rel = 'stylesheet' href='{% static "css/base.css" %}'/>
<div class="col">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src='{% static "img/iima.png" %}' alt="IIMA" />
      <div class="caption">
<<<<<<< HEAD
        <h1>Golbal Supply Chain Management</h1>
=======
        <h1>Operations Strategy Case</h1>
>>>>>>> 0bf8b819a898f865f77233b064c71891fa814275
        <p>...</p>
        <p><a href="{% url 'case:case_intro' %}" class="btn btn-primary" role="button">Play</a></p>
      </div>
    </div>
  </div>
</div>

<div class="col">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="basic/iima.png" alt="...">
      <div class="caption">
        <h3>Marketing Strategy Case</h3>
        <p>...</p>
        <p><a href="#" class="btn btn-primary" role="button">Play</a></p>
      </div>
    </div>
  </div>
</div>

<div class="col">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="basic/iima.png" alt="...">
      <div class="caption">
        <h3>Logistic Strategy Case</h3>
        <p>...</p>
        <p><a href="#" class="btn btn-primary" role="button">Play</a></p>
      </div>
    </div>
  </div>
</div>


{%  endblock %}

templates/case/intro.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
 <h3>Hello, {{ user.username }}. Let's play the game </h3>
</div>

{% block jumbotron %}
<div class="jumbotron">
		  <h3>Candy Manufacturing Company</h3>
		  <p>Welcome to the case simulation of candy manufacturing company, Let's Go Big. Here you'll get a first hand experience of running a company and learn how to manage team and be a good team player.</p>
		  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
</div>
{% endblock %}


<div class="row"><div class="page-header"><h2>How to play<small> Easy to learn </small></h2></div></div>


	
<div class="row">
	  <div class="col-md-4">
		  <h3>Step 1 <span class="label label-default"></span></h3>
		  <p> Aditya Gupta is super coool youououou hdvljwhfg veigrhvbivhbhvpiu hbvpiuvh bvpiug bvpiuefgvre </p>
	  </div>
	 <div class="col-md-4">
			<h3>Step 2 <span class="label label-default"></span></h3>
			 <p> Aditya Gupta is super coool youououou hdvljwhfg veigrhvbivhbhvpiu hbvpiuvh bvpiug bvpiuefgvre </p>
	 </div>
	  <div class="col-md-4">
			<h3>Step 3 <span class="label label-default"></span></h3>
			 <p> Aditya Gupta is super coool youououou hdvljwhfg veigrhvbivhbhvpiu hbvpiuvh bvpiug bvpiuefgvre </p>
	  </div>
</div>

<div class="page-header"><h3>Meet The Team<small> They are the pillars </small></h3></div>

<div class="row">
	  <div class="col-md-4">
	    <div class="thumbnail">
	      <img src="img/iima.png" alt="Image-Hugh">
	      <div class="caption">
	        <h3>Thumbnail label</h3>
	        <p>...</p>
	        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
	      </div>
	    </div>
	  </div>

	  <div class="col-md-4">
	    <div class="thumbnail">
	      <img src="..." alt="Imgae-Scot">
	      <div class="caption">
	        <h3>Thumbnail label</h3>
	        <p>...</p>
	        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
	      </div>
	    </div>
	  </div>

	  <div class="col-md-4">
	    <div class="thumbnail">
	      <img src="..." alt="Imgae-Scot">
	      <div class="caption">
	        <h3>Thumbnail label</h3>
	        <p>...</p>
	        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
	      </div>
	    </div>
	  </div>
</div>


{% endblock %}
    

templates/case/marketing.html
{% extends 'base.html' %}

{% block content %}
    {% if user.is_authenticated %}
    <h3>Hello, {{ user.username }} </h3>
    {{ user.email }}
    {% endif %}

{% endblock content %}

templates/case/navbar.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header" align="center">
      <a class="navbar-brand" href="#">Global Supply Chain Management</a>
    </div>
    <ul class="nav navbar-nav" align="center">
      <li><a href="{% url 'vendor:intro' %}">Intoduction</a></li>
      <li><a href="{% url 'vendor:design' %}">Design</a></li>
<<<<<<< HEAD
      <li><a href="{% url 'vendor:forcastupdate' id=id %}">Forcast </a></li>
=======
      <li><a href="{% url 'vendor:forcastupdate' id=1 %}">Forcast </a></li>
>>>>>>> 0bf8b819a898f865f77233b064c71891fa814275
      <li><a href="{% url 'vendor:production'  %}">Production</a></li>
      <li><a href="{% url 'vendor:board'  %}">Board</a></li>
    </ul>
  </div>
</nav>

templates/case/planning.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}	

{% block title %} Planning | {{block.super}}{% endblock title %}

{% block content %}

{% for vendor in vendors %}

	{{ vendor }}
{% endfor %}



	<div col-md-4>
 	<form method ='POST' action='' > {% csrf_token %}
 		{{ form|crispy }}
 		<input type = 'submit' value='Save' class= 'btn btn-default' />	
 	</form>
 	</div>
 	<div col-md-4>
 	<p> Love you babay</p>
 	</div>


	<div .col-md-4>
	<table class="table">
	    <thead>
	        <tr>
	            <th>Row</th>
	            <th>First Name</th>
	            <th>Last Name</th>
	            <th>Email</th>
	        </tr>
	    </thead>
	    <tbody>
	        <tr>
	            <td>1</td>
	            <td>John</td>
	            <td>Carter</td>
	            <td>johncarter@mail.com</td>
	        </tr>
	        <tr>
	            <td>2</td>
	            <td>Peter</td>
	            <td>Parker</td>
	            <td>peterparker@mail.com</td>
	        </tr>
	        <tr>
	            <td>3</td>
	            <td>John</td>
	            <td>Rambo</td>
	            <td>johnrambo@mail.com</td>
	        </tr>
	    </tbody>
	</table>


{% endblock content %}

templates/case/sidebar.html
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

<div class="nav-side-menu">
    <div class="brand">Brand Logo</div>
    <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
  
        <div class="menu-list">
  
            <ul id="menu-content" class="menu-content collapse out">
                <li>
                  <a href="#">
                  <i class="fa fa-dashboard fa-lg"></i> Dashboard
                  </a>
                </li>

                <li  data-toggle="collapse" data-target="#products" class="collapsed active">
                  <a href="#"><i class="fa fa-gift fa-lg"></i> UI Elements <span class="arrow"></span></a>
                </li>
                <ul class="sub-menu collapse" id="products">
                    <li class="active"><a href="#">CSS3 Animation</a></li>
                    <li><a href="#">General</a></li>
                    <li><a href="#">Buttons</a></li>
                    <li><a href="#">Tabs & Accordions</a></li>
                    <li><a href="#">Typography</a></li>
                    <li><a href="#">FontAwesome</a></li>
                    <li><a href="#">Slider</a></li>
                    <li><a href="#">Panels</a></li>
                    <li><a href="#">Widgets</a></li>
                    <li><a href="#">Bootstrap Model</a></li>
                </ul>


                <li data-toggle="collapse" data-target="#service" class="collapsed">
                  <a href="#"><i class="fa fa-globe fa-lg"></i> Services <span class="arrow"></span></a>
                </li>  
                <ul class="sub-menu collapse" id="service">
                  <li>New Service 1</li>
                  <li>New Service 2</li>
                  <li>New Service 3</li>
                </ul>


                <li data-toggle="collapse" data-target="#new" class="collapsed">
                  <a href="#"><i class="fa fa-car fa-lg"></i> New <span class="arrow"></span></a>
                </li>
                <ul class="sub-menu collapse" id="new">
                  <li>New New 1</li>
                  <li>New New 2</li>
                  <li>New New 3</li>
                </ul>


                 <li>
                  <a href="#">
                  <i class="fa fa-user fa-lg"></i> Profile
                  </a>
                  </li>

                 <li>
                  <a href="#">
                  <i class="fa fa-users fa-lg"></i> Users
                  </a>
                </li>
            </ul>
     </div>
</div>

templates/case/supply.html
{% extends 'base.html' %}

{% block content %}
    {% if user.is_authenticated %}
    <h3>Hello, {{ user.username }} </h3>
    {{ user.email }}
    {% endif %}

{% endblock content %}