new/urls.py
from django.conf.urls import url
from django.contrib import admin

from simuli import views

from .views import (
    IntroView,

    TeamView,
    ProductView,
    ProductionView,
    SupplyView,
    BoardView,
    ResultView,
    ProductUpdateView,
    ForcastCreateView,
    SupplyCreateView,
    VendorCreateView,
    UserProfileUpdateView,
    SupplyUpdateView,
    SupplyUpdateView2,
    SupplyUpdateView3,
    SupplyUpdateView4,
    SendInvite,
    TestView,
    ReportView,

    )

urlpatterns = [
    url(r'^$', IntroView, name='intro'),
    url(r'^design$', ProductView, name='design'),
    url(r'^team', TeamView, name='team'),
    url(r'^production', ProductionView, name='production'),
    url(r'^supply$', SupplyView, name='supply'),
    url(r'^board', BoardView, name='board'),
    url(r'^result', ResultView, name='results'),
    url(r'^test', TestView, name='test'),
    url(r'^report', ReportView, name='report'),
    url(r'^invite', SendInvite.as_view(), name='invite'),

    # url(r'^videos/(?P<pk>\d+)/$', VideoDetailView.as_view(), name='video-detail'),
    #url(r'^(?P<slug>[\w-]+)/$', VideoDetailView.as_view(), name='detail'),
    url(r'^forcast/(?P<pk>[0-9]+)/', ForcastCreateView.as_view(), name='forcastupdate'),
    url(r'^createsupply$', SupplyCreateView, name='supplycreate'),
    url(r'^design/(?P<pk>[0-9]+)/', ProductUpdateView.as_view(), name='designupdate'),
    url(r'^createvendor$', VendorCreateView, name='createvendor'),
    url(r'^profile/(?P<pk>[0-9]+)/', UserProfileUpdateView.as_view(), name='profileupdate'),
    url(r'^supply/(?P<pk>[0-9]+)/', SupplyUpdateView.as_view(), name='supplyupdate'),
    url(r'^2supply/(?P<pk>[0-9]+)/', SupplyUpdateView2.as_view(), name='supplyupdate2'),
    url(r'^3supply/(?P<pk>[0-9]+)/', SupplyUpdateView3.as_view(), name='supplyupdate3'),
    url(r'^4supply/(?P<pk>[0-9]+)/', SupplyUpdateView4.as_view(), name='supplyupdate4'),
     
    #url(r'^(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),  



]

simuli/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from .views import HomeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^new/', include('new.urls', namespace='vendor')),
    url(r'^accounts/', include('allauth.urls')),
    #url(r'^invitations/accept-invite/(?P<key>\w+)/?$', AcceptInviteView.as_view(), name='accept-invite'),
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),





    
    url(r'^new/', include('new.urls', namespace='vendor')),
    url(r'^accounts/', include('allauth.urls')), 
    	


]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html

{% load staticfiles %}
<head>
    <script
  src="https://code.jquery.com/jquery-3.2.1.js"
  integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
  crossorigin="anonymous"></script>

</head>



{% include 'head_css.html' %}
    <body>
    {% if user.is_authenticated %}
    {% include 'new/navbar.html' %}

    {% else %}
    {% include 'new/home.html' %}
    {% endif %}



            {% block content %}
            {% endblock %}




{% include "javascript.html" %}

    <script>
    $(document).ready(function(){
        {% block jquery %}
        {% endblock %}
    });
    </script>
</body>

</html>

templates/head_css.html
{% load staticfiles %}
<html>
    <head>

    <div class="page-header" style="background-color:#ADD8E6;">
  <h1 style="text-align:center;">IIM-A Case Simulation  <p><small>Learn to become better leaders</small></p></h1>

    </div>
        <title>IIMA-Case Simulation</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

        <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.dataTables.min.css">
         

    </head>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">


<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/data.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>

templates/home.html
{% extends 'base.html' %}


{% block jquery %}

$(document).ready(function(){

$("h2").css({"font-style":"italic", "font-size":"175%", "color":"#696969"});
$("h3").css({"font-size":"175%", "color":"#008080"});
$("p").css("color", "#2F4F4F"); $("li").css("color", "#CD5C5C");$("li").css("font-style", "bold");$("small").css({"font-style":"italic", "color":"#696969"});
});


{% endblock %}



{% block content %}
<div class="container">
    {% if user.is_authenticated %}
    <h2>Hello, {{ user.username }} </h2>

    

<div class="row">
    <div class="spacer">

    <div class="col-md-6">
        <h3> Welcome to the case simulation of Global Supply Chain Management</h3>
        <p>  We'll be working on this project to give you an idea of what's it like to run a company and manage the supply chain.   </p>
        <p> You'll be learning the followings</p>
        <div id="list">
        <li> Manage a team  </li>
        <li> Manage suppliers </li>
        <li> Manage Company Budget</li>
        <li> Make decision using analytics </li>
        <li> <a href ="#">Click to see overview of simulation goals and experience</a></li>
        </div>
    </div>
    <div class="col-md-4">
        <p></p>
        <p></p>

        <a href="{% url 'vendor:profileupdate' pk=request.user.id %}" type="button" class="btn btn-primary btn-lg">Click to start the simulation</a>
        <p></p>


    </div>

    <div class="col-md-6">
        <p></p>

        <h3><a href ="#">Click to see the teaching notes</a> <small> Instructor guide to the simulation.</small></h3>
        <p></p>


    </div>
    <div class="col-md-6">

        <h3><a href="#">Simulation Previews</a></h3> <small> Quick views of the simulation from the student or instructor perspective. The administrator view includes sample
        student data.</small>

    </div>





</div>
</div>
</div>
{% endif %}



{% endblock content %}

templates/javascript.html
{% load staticfiles %}
<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- <script src="https://js.braintreegateway.com/v2/braintree.js"></script> -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.js"></script>
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
    <script src="//cdn.datatables.net/buttons/1.3.1/js/buttons.flash.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/pdfmake.min.js"></script>
    <script src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/vfs_fonts.js"></script>
    <script src="//cdn.datatables.net/buttons/1.3.1/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="//cdn.datatables.net/buttons/1.3.1/js/buttons.print.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.6/numeral.min.js"></script>
    <script src="{% static 'js/js.cookie.js' %}"></script>

templates/jquery.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block jquery %}



{% endblock %}


{% block content %}


{{ mo1 }}, {{ e1 }}

{% endblock %}

templates/sidebar.html
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

<div class="nav-side-menu">
    <div class="brand">Brand Logo</div>
    <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
  
        <div class="menu-list">
  
            <ul id="menu-content" class="menu-content collapse out">
                <li>
                  <a href="#">
                  <i class="fa fa-dashboard fa-lg"></i> Dashboard
                  </a>
                </li>

                <li  data-toggle="collapse" data-target="#products" class="collapsed active">
                  <a href="#"><i class="fa fa-gift fa-lg"></i> UI Elements <span class="arrow"></span></a>
                </li>
                <ul class="sub-menu collapse" id="products">
                    <li class="active"><a href="#">CSS3 Animation</a></li>
                    <li><a href="#">General</a></li>
                    <li><a href="#">Buttons</a></li>
                    <li><a href="#">Tabs & Accordions</a></li>
                    <li><a href="#">Typography</a></li>
                    <li><a href="#">FontAwesome</a></li>
                    <li><a href="#">Slider</a></li>
                    <li><a href="#">Panels</a></li>
                    <li><a href="#">Widgets</a></li>
                    <li><a href="#">Bootstrap Model</a></li>
                </ul>


                <li data-toggle="collapse" data-target="#service" class="collapsed">
                  <a href="#"><i class="fa fa-globe fa-lg"></i> Services <span class="arrow"></span></a>
                </li>  
                <ul class="sub-menu collapse" id="service">
                  <li>New Service 1</li>
                  <li>New Service 2</li>
                  <li>New Service 3</li>
                </ul>


                <li data-toggle="collapse" data-target="#new" class="collapsed">
                  <a href="#"><i class="fa fa-car fa-lg"></i> New <span class="arrow"></span></a>
                </li>
                <ul class="sub-menu collapse" id="new">
                  <li>New New 1</li>
                  <li>New New 2</li>
                  <li>New New 3</li>
                </ul>


                 <li>
                  <a href="#">
                  <i class="fa fa-user fa-lg"></i> Profile
                  </a>
                  </li>

                 <li>
                  <a href="#">
                  <i class="fa fa-users fa-lg"></i> Users
                  </a>
                </li>
            </ul>
     </div>
</div>