new/urls.py
from django.conf.urls import url
from django.contrib import admin

from simuli import views

from .views import (
    IntroView,

    TeamView,
    ProductView,
    ProductionView,
    SupplyView,
    BoardView,
    ResultView,
    ProductUpdateView,
    ForcastCreateView,
    SupplyCreateView,
    VendorCreateView,
    UserProfileUpdateView,
    SupplyUpdateView,
    SupplyUpdateView2,
    SupplyUpdateView3,
    SupplyUpdateView4,
    SendInvite,
    TestView,
    ReportView,

    )

urlpatterns = [
    url(r'^$', IntroView, name='intro'),
    url(r'^design$', ProductView, name='design'),
    url(r'^team', TeamView, name='team'),
    url(r'^production', ProductionView, name='production'),
    url(r'^supply$', SupplyView, name='supply'),
    url(r'^board', BoardView, name='board'),
    url(r'^result', ResultView, name='results'),
    url(r'^test', TestView, name='test'),
    url(r'^report', ReportView, name='report'),
    url(r'^invite', SendInvite.as_view(), name='invite'),

    # url(r'^videos/(?P<pk>\d+)/$', VideoDetailView.as_view(), name='video-detail'),
    #url(r'^(?P<slug>[\w-]+)/$', VideoDetailView.as_view(), name='detail'),
    url(r'^forcast/(?P<pk>[0-9]+)/', ForcastCreateView.as_view(), name='forcastupdate'),
    url(r'^createsupply$', SupplyCreateView, name='supplycreate'),
    url(r'^design/(?P<pk>[0-9]+)/', ProductUpdateView.as_view(), name='designupdate'),
    url(r'^createvendor$', VendorCreateView, name='createvendor'),
    url(r'^profile/(?P<pk>[0-9]+)/', UserProfileUpdateView.as_view(), name='profileupdate'),
    url(r'^supply/(?P<pk>[0-9]+)/', SupplyUpdateView.as_view(), name='supplyupdate'),
    url(r'^2supply/(?P<pk>[0-9]+)/', SupplyUpdateView2.as_view(), name='supplyupdate2'),
    url(r'^3supply/(?P<pk>[0-9]+)/', SupplyUpdateView3.as_view(), name='supplyupdate3'),
    url(r'^4supply/(?P<pk>[0-9]+)/', SupplyUpdateView4.as_view(), name='supplyupdate4'),
     
    #url(r'^(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),  



]

simuli/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from .views import HomeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^new/', include('new.urls', namespace='vendor')),
    url(r'^accounts/', include('allauth.urls')),
    #url(r'^invitations/accept-invite/(?P<key>\w+)/?$', AcceptInviteView.as_view(), name='accept-invite'),
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),





    
    url(r'^new/', include('new.urls', namespace='vendor')),
    url(r'^accounts/', include('allauth.urls')), 
    	


]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

new/forms.py
from django import forms
from django.contrib.auth.models import User, Group


from .models import Vendor,Vendor2, Vendor3, Vendor4, Forcast, Product, College

class VendorForm(forms.ModelForm):

    class Meta:
        model = Vendor
        fields = [
            'monthly_order1',
            'start_month1',
            'monthly_order2',
            'start_month2',
            'monthly_order3',
            
            
            'start_month3',
           
]
class VendorForm2(forms.ModelForm):

    class Meta:
        model = Vendor2
        fields = [
            'monthly_order4',
            
            'monthly_order5',
            
            'monthly_order6',
            
            
            
           
]
class VendorForm3(forms.ModelForm):

    class Meta:
        model = Vendor3
        fields = [
            'monthly_order7',
            
            'monthly_order8',
            
            'monthly_order9',
            
            
            
           
]
class VendorForm4(forms.ModelForm):

    class Meta:
        model = Vendor4
        fields = [
            'monthly_order10',
            
            'monthly_order11',
            
            'monthly_order12',
            
            
            
           
]

class ProductForm(forms.ModelForm):
	class Meta:
		model=Product
		fields = [
			'style',
			'storage',
			'extended_battery',
			'durability',
		]

class ForcastForm(forms.ModelForm):
	class Meta:
		model=Forcast
		fields = [
		'forcast',


		]


# class UserProfileForm(forms.ModelForm):
#     group = forms.ModelChoiceField(queryset=Group.objects.all(),
#                                    required=True)
    
#     class Meta:
#         model = User
#         fields = ['first_name', 'last_name', 'email', 'group']


class ProfileForm(forms.ModelForm):
    group = forms.ModelChoiceField(queryset=Group.objects.all(),
                                 required=True)
    
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'group']

new/views.py
from django.http import JsonResponse,HttpResponseRedirect
from django.core.mail import send_mail
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.contrib.auth.models import User, Group 
from invitations.models import Invitation
from invitations.forms import InviteForm
from django.core.urlresolvers import reverse

from braces.views import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView, FormView


from .forms import VendorForm, ProductForm, ForcastForm, ProfileForm, VendorForm2, VendorForm3, VendorForm4
from .models import Vendor, Demand, Forcast, Product, Vendor2, Vendor3, Vendor4

User = get_user_model()



@login_required
def IntroView(request):
    context = {
    'demand': Demand.objects.filter().first(),
    'product': Product.objects.filter().first(),
    'forcast': Forcast.objects.all(),
    'users': User.objects.all(),
    'vendor':Vendor.objects.filter().first(),
    }
    return render(request, "new/introduction.html", context)

@login_required
def TeamView(request):

    return render(request,"new/team.html")



@login_required
def ProductView(request):

    if request.method=="POST":
        form = ProductForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('vendor:design')
    else:
        form = ProductForm

    context = {
    'demand': Demand.objects.all(),
    'mo1': Demand.objects.get(id=1).monthly_forcast,
    'mo2': Demand.objects.get(id=2).monthly_forcast,
    'mo3': Demand.objects.get(id=3).monthly_forcast,
    'mo4': Demand.objects.get(id=4).monthly_forcast,
    'mo5': Demand.objects.get(id=4).monthly_forcast,
    'e1': Demand.objects.get(id=1).employee_name,
    'e2': Demand.objects.get(id=2).employee_name,
    'e3': Demand.objects.get(id=3).employee_name,
    'e4': Demand.objects.get(id=4).employee_name,
    'e5': Demand.objects.get(id=4).employee_name,
    'product':Product.objects.filter(user=request.user).first(),
    
    'form': form
    }
    return render(request, "new/design.html", context)

class ProductUpdateView(LoginRequiredMixin, UpdateView):
    form_class = ProductForm
    model = Product

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return redirect('vendor:design')



@login_required
def ProductionView(request):    
    return render(request, "new/production.html")

@login_required
def VendorCreateView(request):
    form = VendorForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        return redirect('vendor:production')
    else:
        VendorForm  
    context = {
        "vendor": Vendor.objects.all(),
        "demand": Demand.objects.all(),
        'product': Product.objects.all(),
        
        "form":form,
    }
    return render(request, "new/vendor_form.html", context)  


class ForcastCreateView(LoginRequiredMixin, UpdateView):
    form_class = ForcastForm
    model = Forcast
    
      

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ForcastCreateView, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['vendor'] = Vendor.objects.filter(user=self.request.user).first(),
        context['demand'] = Demand.objects.all()
        context['product'] = Product.objects.all()
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return redirect('vendor:production')
        

@login_required
def SupplyView(request):
    context = {
    'vendor': Vendor.objects.filter(user=request.user).first(),
    'vendor2': Vendor2.objects.filter(user=request.user).first(),
    'vendor3': Vendor3.objects.filter(user=request.user).first(),
    'vendor4': Vendor4.objects.filter(user=request.user).first(),
    'forcast': Forcast.objects.get(user=request.user),
    'product': Product.objects.filter(user=request.user).first(),

    }
    return render(request, "new/supply.html", context)

@login_required
def SupplyCreateView(request):

    form = VendorForm()
    if request.method == 'POST':
    
        form = VendorForm(request.POST or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            return HttpResponseRedirect(reverse('vendor:supply'))    
        else:
            form = VendorForm

    context = {
        "demand": Demand.objects.all(),
        "form":form,
        "vendor": Vendor.objects.all(),

    }
    return render(request, "new/supply_form.html", context)

@login_required
def ResultView(request):
    return render(request,"new/result.html")    


class SupplyUpdateView(LoginRequiredMixin, UpdateView):
    form_class = VendorForm
    model = Vendor 

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return redirect('vendor:supply')

class SupplyUpdateView2(LoginRequiredMixin, UpdateView):
    form_class = VendorForm2
    model = Vendor2 


    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return redirect('vendor:supply')

class SupplyUpdateView3(LoginRequiredMixin, UpdateView):
    form_class = VendorForm3
    model = Vendor3 
    

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return redirect('vendor:supply')

class SupplyUpdateView4(LoginRequiredMixin, UpdateView):
    form_class = VendorForm4
    model = Vendor4 
    

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return redirect('vendor:supply')




@login_required
def BoardView(request):
    context = {
    'demand': Demand.objects.filter().first(),
    'product': Product.objects.filter().first(),
    'forcast': Forcast.objects.all(),
    'users': User.objects.all(),
    'vendor':Vendor.objects.filter().first(),
    }

    return render(request,'new/board.html',context)

@login_required
def ReportView(request):
    context = {
    'demand': Demand.objects.filter().first(),
    'product': Product.objects.filter().first(),
    'forcast': Forcast.objects.all(),
    'users': User.objects.all(),
    'vendor':Vendor.objects.filter().first(),
    }

    return render(request,'new/report.html',context)


@login_required
def TestView(request):
    context = {
    
    'invitees':Invitation.objects.filter(inviter_id=request.user.id),
    'invitations': Invitation.objects.all(),
    'accepted':Invitation.objects.filter(inviter_id=request.user.id).filter(accepted=True),
    'inviteescount':Invitation.objects.filter(inviter_id=request.user.id).count(),
    'notaccepted':Invitation.objects.filter(inviter_id=request.user.id).filter(accepted=False)

    }

    return render(request, "new/test.html", context)




class UserProfileUpdateView(LoginRequiredMixin, UpdateView):
    form_class = ProfileForm
    model = User

    def get_initial(self):
        initial = super(UserProfileUpdateView, self).get_initial()
        try:
            current_group = self.object.groups.get()
        except:
            # exception can occur if the edited user has no groups
            # or has more than one group
            pass
        else:
            initial['group'] = current_group.pk
        return initial
        

    def get(self, request, **kwargs):
        self.object = User.objects.get(username=self.request.user)
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context = self.get_context_data(object=self.object, form=form)
        return self.render_to_response(context)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return redirect('vendor:intro')

    
class SendInvite(LoginRequiredMixin, FormView):
    template_name = 'invitations/forms/_invite.html'
    form_class = InviteForm

    
    def dispatch(self, request, *args, **kwargs):
        return super(SendInvite, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        email = form.cleaned_data["email"]

        try:
            invite = form.save(email)
            invite.inviter = self.request.user
            invite.save()
            invite.send_invitation(self.request)
        except Exception:
            return self.form_invalid(form)

        return self.render_to_response(
            self.get_context_data(
                success_message='%s has been invited' % email))

    context ={ 
    
    }

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form), context)






    


# def GroupCreateView(request):
    
#     form = ProfileForm()
#     if request.method == 'POST':
#         form = ProfileForm(request.POST or None)
#         if form.is_valid():
#             instance = form.save(commit=False)
#             instance.user = request.user 
#             instance.save()
#             return redirect('vendor:intro')    
#         else:
#             form = ProfileForm

#     if request.user.profile.type_user=='t':
#         g = Group.objects.get(name='Teacher') 
#         g.user_set.add(request.user)        

           
    

templates/new/Cookies.html
<!-- function setCookie(name, value){
  // Set cookie to `namevalue;`
  // Won't overwrite existing values with different names
  document.cookie = name + value + ';';
}

function getCookie(name){
  // Split by `;`
  var cookie = document.cookie.split(";");
  
  // iterate over cookie array
  for(var i  = 0; i < cookie.length; i++){
    var c = cookie[i];
    // if it contains string "click"
    if(/click/.test(c))
       return true;
  }
  // cookie does not exist
  return false;
}

// Set clicked to either the existing cookie or false
var clicked = getCookie("click") || false;

// Check if it was clicked before
alert(clicked);

// Get the button
var button = document.getElementById("update");

// If it had been clicked, diable button
if (clicked) button.disabled = true;

// Add event listener 
// When button clicked, set `click` cookie to true 
// and disable button
button.addEventListener("click", function(){
  setCookie("click", "true");
  button.disabled = true;
}, false);
 -->

templates/new/board.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block jquery %}



$("h2").css({"font-style":"italic", "font-size":"175%", "color":"#696969"});
$("h3").css({"font-size":"175%", "color":"#008080"});
$("p").css("color", "#2F4F4F"); $("li").css("color", "#CD5C5C");$("li").css("font-style", "bold");$("small").css({"font-style":"italic", "color":"#696969"});

var style = "{{ product.style }}";
var storage = "{{ product.durability }}";
var durability = "{{ product.durability }}";
var extended_battery = "{{ product.extended_battery }}";
var vote1 = "No";
var vote2 = "No";
var vote3 = "No";
var vote4 = "No";
var comment1 = "fghjkl; fghjkl fghjk";
var comment2 = "fghj ghjk fghj fghj fghj";
var comment3 = "ghjk ghjk fgh g ";
var comment4 = "fghjkfghj fghjk dfghjk dfghj";


if(style==="True"){
  vote1 = "Yes";
  comment1 = "aditya hkjghjk fgjhghj ghjhgjk ghghjk ghjk ghhjkjl ghhjjk ghjh";
};

if(storage==="True"){
  vote2 = "Yes";
  comment2 = "aditya hkjghjk fgjhghj ghjhgjk ghghjk ghjk ghhjkjl ghhjjk ghjh";
};
if(durability==="True"){
  vote3 = "Yes";
  comment3 = "aditya hkjghjk fgjhghj ghjhgjk ghghjk ghjk ghhjkjl ghhjjk ghjh";
};
if(extended_battery==="True"){
  vote4 = "Yes";
  comment4 = "aditya hkjghjk fgjhghj ghjhgjk ghghjk ghjk ghhjkjl ghhjjk ghjh";
};

$("#board1").click(function(){
  $("#vote1").html(vote1);
  $("#p1").html(comment1);
});
$("#board2").click(function(){
  $("#vote2").html(vote1);
  $("#p2").html(comment1);
});
$("#board3").click(function(){
  $("#vote3").html(vote1);
  $("#p3").html(comment1);
});
$("#board4").click(function(){
  $("#vote4").html(vote1);
  $("#p4").html(comment1);
});





{% endblock %}


{% block content %}
<div class="container">
<div class="row">

<div class="col-md-6">
    <h1> Boardroom </h1>
<h3> Board Review </h3>

<p> <b>{{ user}}</b>        Your company's board will now discuss your performance. Each board member has a particular area of interest and will give you some advice in that area.
</p><p>
    It pays to listen to your board members, as they will give valuable advice and look for improvements each year.</p>
</div>
<div class="col-md-6" align="center" >
<h2> Votes </h2>
<table class="table">
  <thead>
    <tr>
      
      <th>Board Member</th>
      <th>Vote</th>
      
    </tr>
  </thead>
  <tbody>
    <tr>
      <th >Jason</th>
      <td id="vote1">-</td>
      
    </tr>
    <tr>
      <th scope="row">Roy</th>
      <td id="vote2">-</td>
      
    </tr>
    <tr>
      <th scope="row">Shweta</th>
      <td id="vote3">-</td>
      
    </tr>
     <tr>
      <th scope="row">Bihari</th>
      <td id="vote4">-</td>
      
    </tr>
  </tbody>
</table>


</div>
</div>


<div class="row" style="padding:50px;">

<div class="col-md-3">
    <figure class="figure">
  <img src='{% static "img/michale.png" %}' class="figure-img img-fluid rounded" alt="Jason." width="154" height="156">
  <figcaption class="figure-caption"><button id="board1" type="button" class="btn btn-primary"><h4>Jason</h4></button></figcaption>
  <p id="p1">I am aditya I am adityaI am adityaI am adityaI am adityaI am adityaI am adityaI am adityaI am adityaI am adityaI am aditya </p>
</figure>

</div>
<div class="col-md-3">

    <figure class="figure">
  <img src='{% static "img/grands.jpg" %}' class="figure-img img-fluid rounded" alt="Jason." width="154" height="156">
  <figcaption class="figure-caption"><button id="board2" type="button" class="btn btn-primary"><h4>Roy</h4></button></figcaption>
  <p id="p2">I am aditya I am adityaI am adityaI am adityaI am adityaI am adityaI am adityaI am adityaI am adityaI am adityaI am aditya </p>
</figure>

    <p></p>
</div>

<div class="col-md-3">
    <figure class="figure">
  <img src='{% static "img/gob.jpg" %}' class="figure-img img-fluid rounded" alt="Jason." width="154" height="156">
  <figcaption class="figure-caption"><button id="board3" type="button" class="btn btn-primary"><h4>Shweta</h4></button></figcaption>
  <p id="p3">I am aditya I am adityaI am adityaI am adityaI am adityaI am adityaI am adityaI am adityaI am adityaI am adityaI am aditya </p>
</figure>

    </div>
<div class="col-md-3">
    <figure class="figure">
  <img src='{% static "img/bob.jpg" %}' class="figure-img img-fluid rounded" alt="Jason." width="154" height="156">
  <figcaption class="figure-caption"><button id="board4" type="button" class="btn btn-primary"><h4>Bihari</h4></button></figcaption>
  <p id="p4">I am aditya I am adityaI am adityaI am adityaI am adityaI am adityaI am adityaI am adityaI am adityaI am adityaI am aditya </p>
</figure>



</div>

</div>


{% endblock content %}

templates/new/demand_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='Update' />
</form>

<div class='row'>
    
<table class="table">
  <thead class="thead-default">
  

  <tr>
      
    
      <th>Employee</th>
      <th>Monthly </th>
      
      <th>Style</th>
      <th>Flavour</th>
      <th>Discount</th>
      <th>Marketing</th>
    </tr>
    
    <tr>
        
        

    {% for item in demand %}
        <th>{{ item.employee_name_1 }}</th>
        
        <td>{{ item.monthly_demand_1 }}</td>
        
        <td>{{ item.monthly_demand_flavour_1 }}</td>
        <td>{{ item.monthly_demand_style_1 }}</td>
        <td>{{ item.monthly_demand_marketing_1 }}</td>
        
        
    {% endfor %}
        
        <!-- <li><input type="checkbox" name="Malai">Malai</li> -->
      
      
    </tr>
    <tr>
        
        

    {% for item in demand %}
        <th>{{ item.employee_name_2 }}</th>
        
        <td>{{ item.monthly_demand_2 }}</td>
        
        <td>{{ item.monthly_demand_flavour_2 }}</td>
        <td>{{ item.monthly_demand_style_2 }}</td>
        <td>{{ item.monthly_demand_marketing_2 }}</td>
        <td>{{ item.monthly_demand_discount_2 }}</td>
        
    {% endfor %}
        
        <!-- <li><input type="checkbox" name="Malai">Malai</li> -->
      
      
    </tr>
    <tr>
        
        

    {% for item in demand %}
        <th>{{ item.employee_name_3 }}</th>
        
        <td>{{ item.monthly_demand_3 }}</td>
        
        <td>{{ item.monthly_demand_flavour_3 }}</td>
        <td>{{ item.monthly_demand_style_3 }}</td>
        <td>{{ item.monthly_demand_marketing_3 }}</td>
        <td>{{ item.monthly_demand_discount_3 }}</td>
        
    {% endfor %}
        
        <!-- <li><input type="checkbox" name="Malai">Malai</li> -->
      
      
    </tr>
    <tr>
        
        

    {% for item in demand %}
        <th>{{ item.employee_name_4 }}</th>
        
        <td>{{ item.monthly_demand_4 }}</td>
        
        <td>{{ item.monthly_demand_flavour_4 }}</td>
        <td>{{ item.monthly_demand_style_4 }}</td>
        <td>{{ item.monthly_demand_marketing_4 }}</td>
        <td>{{ item.monthly_demand_discount_4 }}</td>
        
    {% endfor %}
        
        <!-- <li><input type="checkbox" name="Malai">Malai</li> -->
      
      
    </tr>


    <tr>
      
    
      <th>Value</th>
      <th>Average</th>
      <th>S-D </th>
      
     
    </tr> 

    <tr>
        
        

    {% for item in demand %}
        <th>Style</th>
        
        <td>1241</td>
        <td>----</td>
        
    <tr>    
        <th>Flavour</th>
        <td>894</td>
        <td>----</td>
        
    </tr>    
    <tr>    
        <th>Discount</th>
        <td>1483</td>
        <td>----</td>
        
    </tr>     
    <tr>    
        <th>1</th>
        <td>{{ item.monthly_demand_marketing_average}}</td>
        <td>----</td>
        
    </tr> 
    {% endfor %}

    
   
  </thead>
  <tbody>
</tbody>
</table>  
</div>




{% endblock content %}

templates/new/product_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
<div class="row">
<div class="col-md-4">
<h1>Choose options </h1>
<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='Update' />
</form>
</div>
</div>
</div>



{% endblock content %}

templates/new/production.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block title %}Production | {{ block.super }}{% endblock title %}

{% block jquery %}

$(document).ready(function(){

$("h2").css({"font-style":"italic", "font-size":"175%", "color":"#696969"});
$("h3").css({"font-size":"175%", "color":"#008080"});
$("p").css("color", "#2F4F4F"); $("li").css("color", "#CD5C5C");$("li").css("font-style", "bold");$("small").css({"font-style":"italic", "color":"#696969"});
});
$('.carousel').carousel({
    interval: false
})


{% endblock %}

{% block content %}
<div class="container">
<div class="row">
<h2> Production Room </h2>
<div class="col-md-8">
    <p>Congratulations. You have successfully given the board your demand estimates. You now need to make some key decisions on how to fulfill this demand.
</p><p>
To increase production flexibility, management has decided to outsource all manufacturing, and you have identified four contract manufacturers.</p>
</div>
<div class="col-md-4" style="padding:20px;">
    <a href="{% url 'vendor:supplyupdate' pk=request.user.id %}" type="button" class="btn btn-primary btn-lg">Choose Suppliers     </a>


</div>
</div>

<div class="row">
    <h3>Talk to Procurement</h3>

<div class="col-md-6" style="padding:20px;">
{% include 'new/sliderprod.html' %}
</div>
</div>

</div>
<div class="row">
<div class="col-md-8">
    <div class="container" id="tourpackages-carousel">

      <div class="row">

        <div class="col-xs-18 col-sm-6 col-md-3">
          <div class="thumbnail">
            <img src='{% static "img/steve.jpg" %}' alt=""  width="154" height="156">
              <div class="caption">
                <h4>	Wayne Enterprises</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, soluta, eligendi doloribus sunt minus amet sit debitis repellat. Consectetur, culpa itaque odio similique suscipit</p>

            </div>
          </div>
        </div>

        <div class="col-xs-18 col-sm-6 col-md-3">
          <div class="thumbnail">
            <img src='{% static "img/dwight.jpg" %}' alt=""  width="154" height="156">
              <div class="caption">
                <h4>Chopra Company</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, soluta, eligendi doloribus sunt minus amet sit debitis repellat. Consectetur, culpa itaque odio similique suscipit</p>

            </div>
          </div>
        </div>

        <div class="col-xs-18 col-sm-6 col-md-3">
          <div class="thumbnail">
            <img src='{% static "img/fatty.jpg" %}' alt=""  width="154" height="156">
              <div class="caption">
                <h4>Carl and Sons</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, soluta, eligendi doloribus sunt minus amet sit debitis repellat. Consectetur, culpa itaque odio similique suscipit</p>

            </div>
          </div>
        </div>



      </div><!-- End row -->

    </div><!-- End container -->

</div>
</div>
</div>







{% endblock content %}

templates/new/test.html
Hi




<p>{{ inviteescount }}</p>
<p>{{ notaccepted }}</p>

templates/new/vendor2_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>Form</h1>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='Update' />
</form>

{% endblock content %}